### ISSUE TITLE
Overleaf error

### ISSUE THREAD

**Issue by LeeWlving** [YangLaTeX/hitszbeamer#1]
Package natbib Error: Bibliography not compatible with author-year citations.(natbib) Press <return> to continue in numerical citation style.
把zip传到，出现了这个，请问一下这个怎么解决呢？

**Comment by YangLaTeX** [comment]
模板设定的是numerical citation style，不支持 author-year citations。要改的话，在dtx文件中调用 natbib 处更改即可
